### ISSUE TITLE
disk quota exceeded error when processing HSOFS mesh on Hera

### ISSUE THREAD

**Issue by zacharyburnettNOAA** [noaa-ocs-modeling/ensemble_perturbation#14]
```bash
[2021-01-08 18:16:18,523] configuration.adcirc INFO    : writing config to "/scratch2/COASTAL/coastal/save/shared/repositories/ensemble_perturbation/examples/data/configuration/hsofs/nems_hsofs_test"
Traceback (most recent call last):
  File "single_hsofs_run.py", line 54, in <module>
    spinup=timedelta(days=12.5),
  File "/scratch2/COASTAL/coastal/save/shared/repositories/ensemble_perturbation/ensemble_perturbation/configuration/adcirc.py", line 198, in write_adcirc_configurations
    driver.write(run_directory, overwrite=True)
  File "/scratch2/COASTAL/coastal/save/shared/miniconda3/envs/ensemble_perturbation/lib/python3.7/site-packages/adcircpy/driver.py", line 367, in write
    self.mesh.write_fort14(path, overwrite)
  File "/scratch2/COASTAL/coastal/save/shared/miniconda3/envs/ensemble_perturbation/lib/python3.7/site-packages/adcircpy/mesh/mesh.py", line 372, in write_fort14
    super().write(path, overwrite, 'gr3')
  File "/scratch2/COASTAL/coastal/save/shared/miniconda3/envs/ensemble_perturbation/lib/python3.7/site-packages/adcircpy/mesh/base.py", line 81, in write
    f.write(self.ascii_string(fmt))
OSError: [Errno 122] Disk quota exceeded
```

**Comment by zacharyburnettNOAA** [comment]
@saeed-moghimi-noaa found this explanation:
https://anaconda.zendesk.com/hc/en-us/articles/360024036713-CondaError-OSError-122-Disk-quota-exceeded-and-Changing-the-Default-Package-Directory
> While using Anaconda with a fixed size home space, a user may encounter the following error
